version: 0.0
os: linux
files:
- source: /
  destination: /home/ec2-user
hooks:
  AfterInstall:
  - location: fix_previleges.sh
    timeout: 300
  ApplicationStart:
  - location: start_server.sh
    timeout: 300
  ApplicationStop:
  - location: stop_server.sh
    timeout: 300
